export const GET_ALLSPACELAUNCHES = 'GET_ALLSPACELAUNCHES';
export const GET_ALLSPACELAUNCHES_SUCCESS = 'GET_ALLSPACELAUNCHES_SUCCESS';
export const GET_ALLSPACELAUNCHES_ERROR = 'GET_ALLSPACELAUNCHES_ERROR';

